# Generated by Django 4.2 on 2023-05-18 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='admin',
            new_name='admin1',
        ),
    ]
