# Generated by Django 4.2 on 2023-05-20 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_rename_admin_admin1'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin1',
            name='Contact',
            field=models.BigIntegerField(default='0'),
        ),
    ]
