# Generated by Django 4.2 on 2023-05-24 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Icon', models.CharField(max_length=100)),
                ('Tital', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=10000)),
            ],
        ),
    ]
