# Generated by Django 4.2 on 2023-05-30 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_blogcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tital', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=100)),
                ('Picture', models.FileField(default='', upload_to='')),
                ('Admin_id', models.BigIntegerField()),
                ('Cat_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='management.blogcategory')),
            ],
        ),
    ]
