# Generated by Django 4.2 on 2023-06-03 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_alter_blog_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='Description',
            field=models.TextField(),
        ),
    ]
