# Generated by Django 4.2 on 2023-06-03 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_alter_services_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='Description',
            field=models.TextField(),
        ),
    ]
