# Generated by Django 4.2 on 2023-06-07 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management', '0013_delete_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Picture', models.FileField(default='', upload_to='')),
                ('Subject', models.CharField(max_length=100)),
                ('Comment', models.TextField()),
                ('Blogid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='management.blog')),
            ],
        ),
    ]
