# Generated by Django 4.2.1 on 2023-06-09 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yomapp', '0003_work'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Work',
            new_name='Workcategory',
        ),
    ]
