# Generated by Django 4.2 on 2023-06-10 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yomapp', '0004_rename_work_workcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=100)),
                ('Picture', models.FileField(default='', upload_to='')),
                ('Work_Category', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='yomapp.workcategory')),
            ],
        ),
    ]
