# Generated by Django 4.2 on 2023-06-10 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yomapp', '0005_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='Description',
            field=models.TextField(),
        ),
    ]
