# Generated by Django 4.2.1 on 2023-06-13 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yomapp', '0006_alter_work_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Picture', models.FileField(default='', upload_to='')),
            ],
        ),
    ]
