# Generated by Django 4.2.1 on 2023-06-13 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yomapp', '0007_clients'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='Link',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
